language: python
python: 3.6
services:
  - xvfb
before_script:
  - export DISPLAY=:99.0
  - sleep 3 # give xvfb some time to start
script:
  - make flake8 
  - nosetests -v -I '(evolve|replay).py'
install:
  - pip3 install numpy pandas matplotlib deap flake8
