#!/bin/bash
## Make sure to set PYTHONEXECUTABLE to Python that created this script
export PYTHONEXECUTABLE=/opt/anaconda3/envs/myenv/bin/python
export EXE=/opt/anaconda3/envs/myenv/bin/python
export SCRIPT=/Users/elonarey-costa/Documents/phdCode/NEMO/evolve.py
export ARGS=''

osascript -e 'tell application "Terminal"
   do script "'${EXE}\ /Users/elonarey-costa/Documents/phdCode/NEMO/evolve.py\ '"
end tell
'

